---
title: "HW4"
author: "Avery Davidowitz"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

## Import libraries

```{r, warning=FALSE, message=FALSE}
library(imager)
library(tidyverse)
```



## Download and Plot images

```{r}
num_images <- 17
res <- c(2500, 1200, 3) #res and color channels
shoes <- matrix(0, num_images, prod(res)) 
for(i in 1:num_images){
img <- imager::load.image(paste0("https://github.com/adavidowitz100/DATA605/raw/main/HW4/jpg/",i,".jpg"))
plot(img)
red  <- as.vector(img[,,1])
green  <- as.vector(img[,,2])
blue  <- as.vector(img[,,3])
shoes[i,] <- (t(c(red, green, blue)))
}
shoes <- t(shoes)
shoes_df = as.data.frame((shoes))

```
## Scale shoe data and determine eigenvalues of covariance matrix

```{r}
scaled <- scale(shoes_df)
sigma <- cov(scaled)
eig <- eigen(sigma)
eig_val  <- eig$values
```

## Calculate cumulative variance

```{r}
cvf = cumsum(eig_val) / sum(eig_val)
cvf_df <- as.data.frame(cvf)
thresh = min(which(cvf > .80))
cvf
thresh
```
## Plot cumulative variance

```{r}
ggplot(cvf_df, aes(x = 1:num_images, y = cvf)) + geom_point() +
  labs(title=paste("Cumulative Variance of", num_images, "Shoes"), y="Cumulative Variance", x="Shoes")
```

