---
title: "HW1"
author: "Avery Davidowitz"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Drawing Initials

```{r}
r <- 1
d <- seq(-1, 1,length.out = 1000)
d <- sqrt(r^2 - d^2)

x <- c(seq(.1, .1, length.out = 500),
      seq(-.5, 0, length.out = 500),
      seq(-1, -.5, length.out = 500),
      seq(-.8, -.2, length.out = 500),
      d)

y <- c(seq(-1, 1, length.out = 500),
       seq(1, -1, length.out = 500),
       seq(-1, 1, length.out  =500),
       seq(-.25, -.25,length.out = 500),
       seq(-1, 1, length.out = 1000))

z <- rbind(x,y)

plot(y~x, xlim=c(-3,3),ylim=c(-3,3))
```
## Shear

```{r}
x11()
for (i in seq( 0, 3, length.out = 15)) {
  Z<-apply(z,2,function(x) x %*% matrix(c(1,0,i,1),nrow=2,ncol=2))
  plot(Z[2,]~Z[1,], xlim=c(-3,3), ylim=c(-3,3))
}
```

## Scaling

```{r}
x11()
for (i in seq(1, .1,length.out=15)) {
  Z<-apply(z,2,function(x) x %*% matrix(c(i,0,0,i),nrow=2,ncol=2))
   plot(Z[2,]~Z[1,], xlim=c(-3,3), cex=.5,ylim=c(-3,3))
}
```

## Rotation
```{r}
x11()
for (i in seq(0, pi*2, length.out = 15)) {
  Z<-apply(z,2,function(x) x %*% matrix(c(cos(i),sin(i),-sin(i),cos(i)),nrow=2,ncol=2))
   plot(Z[2,]~Z[1,], xlim=c(-3,3), ylim=c(-3,3))
}
```

